import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "SkillBridge terms of service.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <header className="border-b border-white/5 px-6 py-5">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link href="/" className="text-xl font-bold tracking-tight">
            <span className="text-white">Skill</span>
            <span className="text-blue-400">Bridge</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="mb-8 text-3xl font-bold">Terms of Service</h1>
        <div className="space-y-6 text-sm leading-relaxed text-zinc-400">
          <p>
            <strong className="text-zinc-300">Last updated:</strong>{" "}
            {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Service</h2>
            <p>
              SkillBridge provides AI-generated career roadmaps and mock interview evaluations.
              The free tier includes roadmap generation. Mock interviews are available as a one-time
              purchase.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">AI-generated content</h2>
            <p>
              Roadmaps, interview questions, and evaluations are generated by AI. While we strive
              for accuracy, this content is for guidance only and should not be treated as
              professional career advice. Always use your own judgment.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Payments & refunds</h2>
            <p>
              Mock interview access is a one-time payment of $9 USD processed through Stripe.
              Since the product is delivered digitally and immediately, refunds are handled on a
              case-by-case basis. Contact{" "}
              <a href="mailto:support@tryskillbridge.com" className="text-blue-400 hover:underline">
                support@tryskillbridge.com
              </a>{" "}
              if you experience any issues.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Acceptable use</h2>
            <p>
              You agree not to abuse, spam, or attempt to exploit the service. We reserve the right
              to restrict access to users who violate these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Data & privacy</h2>
            <p>
              Your use of SkillBridge is also governed by our{" "}
              <Link href="/privacy" className="text-blue-400 hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Limitation of liability</h2>
            <p>
              SkillBridge is provided &ldquo;as is&rdquo; without warranties. We are not liable for
              career decisions made based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">Contact</h2>
            <p>
              Questions about these terms? Email{" "}
              <a href="mailto:support@tryskillbridge.com" className="text-blue-400 hover:underline">
                support@tryskillbridge.com
              </a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
